#
###################################
# Site wide configuration
####################################
#
title:       " - sbugzu - "
description: "sbugzu personal blog, soft"
url:         # the base hostname & protocol for your site

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Chongqing
encoding:          utf-8
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  #enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: sbugzu
  avatar: bug.png
  job: "搬砖~"
  bio: "立志为善由得我，只是行出来由不得我。"
  email:
  disqus-shortname: sbugzu
  twitter:
  facebook:
  google:
    plus:
    analytics: "UA-36278961-2"
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
